
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://murvbwhegsauxlkgzcvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11cnZid2hlZ3NhdXhsa2d6Y3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTAwODIsImV4cCI6MjA2MjI4NjA4Mn0.7QLmsi609pt9YVa9lG48NFU0wFY48McBSYc4BCaQu2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
